### ISSUE TITLE
Get full record

### ISSUE THREAD

**Issue by paglias** [internalfx/mindex#2]
Great project!

Looking at the README and the tests I noticed that all methods (`.get()`, `.getAll()`, `.query()`) only return the records' IDs, there's a way to access the full record object?

**Comment by internalfx** [comment]
There isn't....

The reason why is that mindex doesn't store the full record.

My suggestion would be to keep your records in an object, by ID.

I Just pushed a release that exposes the lower level API. That might make it more obvious how to use it.

`insertRecord`, `updateRecord` etc... are actually just convenience methods.

**Comment by paglias** [comment]
@internalfx I see, using an object with IDs as keys seems good enough
