### ISSUE TITLE
mindex not working as on tin

### ISSUE THREAD

**Issue by monolithpl** [internalfx/mindex#6]
i don't have time to debug your code myself, but after running a sample script from your examples i've got to conclude that it's simply not working as designed.

var Mindex = require('mindex')
var index = Mindex(['age'])

index.insertRecord({
  id: 1,
  name: 'John',
  city: 'Denver',
  age: 35
})

index.insertRecord({
  id: 2,
  name: 'Betty',
  city: 'Denver',
  age: 37
}) 

console.log(index.get('Denver'))
// returns [2]
// and unfortunately not [1,2] as it should.

**Comment by internalfx** [comment]
You are indexing by Age...

`var index = Mindex(['age'])`

And then querying by City...

`console.log(index.get('Denver'))`

Try `var index = Mindex(['city'])`

**Comment by monolithpl** [comment]
great. thanks for the reply!
i could also index by both, i guess:
var mindex = Mindex(['city', 'age'])

**Comment by internalfx** [comment]
Just to be clear, indexing by both does not mean you can query by both anyway you want...

If you index like this...

`var mindex = Mindex(['city', 'age'])`

Then you must query like this....

`console.log(index.get('Denver', 25))`

**Comment by monolithpl** [comment]
i see.
much impressed by the precision and promptness of your replies. much thanks!
